### ISSUE TITLE
I would like to know what we can expect as to bug fixes.

### ISSUE THREAD

**Issue by Mikhail-Zex** [H4KKR/pytubeX#18]
I'm the active maintainer and dev on [spotify-downloader](https://github.com/spotDL/spotify-downloader), we plan to make a shift to pytubeX from pytube3. Assuming we have bugs, how fast can we expect fixes and patches?

**Comment by H4KKR** [comment]
Hi Mikhail-Zex, 
Honestly I don't know how fast I'll be able to get round to them. I've just cleared a backlog of pulls, but yes sorry I'm not sure.

**Comment by Mikhail-Zex** [comment]
Ok cool. We actually reverted to the original pytube.

We suggest PytubeX for ppl who run into glitches with the original pytube.
