### ISSUE TITLE
Playlist is empty

### ISSUE THREAD

**Issue by penut85420** [H4KKR/pytubeX#7]
Version: `pytubeX==0.1.2`
Code:
```python
In [1]: from pytube import Playlist

In [2]: playlist = Playlist('https://www.youtube.com/playlist?list=PL326E728CF5AA4CBF')

In [3]: playlist.video_urls
Out[3]: []
```
I'm not sure if this is related to this [issue](https://github.com/nficano/pytube/issues/670).

**Comment by krishna-bala** [comment]
I had this same issue, perhaps this will resolve it for you. I use python3 (Python 3.6.9) and initially when I had this issue, I had installed pytube3 via 
`pip3 install --upgrade pytube3` 

To fix, I uninstalled via 
`pip3 uninstall pytube3` 
and then re-installed via 
`git clone git://github.com/nficano/pytube.git`
`cd pytube`
`install .`

After reinstalling via git clone, playlist.video_urls returned a non-empty array when given a correct playlist link.

**Comment by penut85420** [comment]
@krishna-bala thanks, it works!

**Comment by serranoarevalo** [comment]
I was having this error and the above solution did not work.

This did the trick:

```pip install git+https://github.com/nficano/pytube.git```
